import {
  MATERIALIZED_FIXTURE_PRODUCTION_DENYLIST_ID,
  MATERIALIZED_FIXTURE_ROOT_ID,
  MATERIALIZED_FIXTURE_SPREADSHEET_ID,
} from "./cutover_witness_fixture";

export const CUTOVER_WITNESS_WORKER_SERVICE = "workos-cutover-witness";
export const CUTOVER_WITNESS_WORKER_URL =
  "https://workos-cutover-witness.lennyliu01.workers.dev";
export const CUTOVER_WITNESS_FORMAL_ROUTE = "/cutover/witness";
export const CUTOVER_WITNESS_READINESS_ROUTE = "/cutover/witness/readiness";
export const CUTOVER_WITNESS_WRANGLER_CONFIG = "wrangler.cutover-witness.jsonc";

export const CUTOVER_WITNESS_CALLER_AUTH_BINDING = "RUNTIME_SECRET";
export const CUTOVER_WITNESS_GOOGLE_CREDENTIAL_BINDING =
  "CUTOVER_WITNESS_GOOGLE_ACCESS_TOKEN";
export const CUTOVER_WITNESS_PROVIDER_AUTH_MODE =
  "GOOGLE_OAUTH_BEARER_ACCESS_TOKEN_EPHEMERAL";
export const CUTOVER_WITNESS_CREDENTIAL_PROVISIONING_MECHANISM =
  "GITHUB_ACTIONS_OIDC_TO_GOOGLE_WIF_TO_DEDICATED_SERVICE_PRINCIPAL_TO_SHORT_LIVED_OAUTH2_ACCESS_TOKEN_TO_CLOUDFLARE_WORKER_SECRET";

export const CUTOVER_WITNESS_GCP_PROJECT_ID = "workos-control-plane";
export const CUTOVER_WITNESS_GCP_PROJECT_NUMBER = "959429469584";
export const CUTOVER_WITNESS_WIF_POOL_FULL_NAME =
  "projects/959429469584/locations/global/workloadIdentityPools/workos-cutover-witness";
export const CUTOVER_WITNESS_WIF_PROVIDER_FULL_NAME =
  "projects/959429469584/locations/global/workloadIdentityPools/workos-cutover-witness/providers/github-workos-d1-runtime";
export const CUTOVER_WITNESS_WIF_AUDIENCE = CUTOVER_WITNESS_WIF_PROVIDER_FULL_NAME;
export const CUTOVER_WITNESS_SERVICE_PRINCIPAL =
  "workos-cutover-witness@workos-control-plane.iam.gserviceaccount.com";
export const CUTOVER_WITNESS_GOOGLE_SCOPE =
  "https://www.googleapis.com/auth/spreadsheets";
export const CUTOVER_WITNESS_REQUESTED_ACCESS_TOKEN_LIFETIME_SECONDS = 1800;
export const CUTOVER_WITNESS_MAXIMUM_ACCESS_TOKEN_LIFETIME_SECONDS = 3600;
export const CUTOVER_WITNESS_EXPIRY_MARGIN_SECONDS = 300;

export const CUTOVER_WITNESS_ROTATION_MODEL_VERSION =
  "CUTOVER_WIF_ROTATION_MODEL_V1";
export const CUTOVER_WITNESS_REVOCATION_MODEL_VERSION =
  "CUTOVER_WIF_REVOCATION_MODEL_V1";
export const CUTOVER_WITNESS_SECRET_NONDISCLOSURE_CONTRACT_VERSION =
  "CUTOVER_WIF_SECRET_NONDISCLOSURE_V1";
export const CUTOVER_WITNESS_CREDENTIAL_LIFECYCLE_ID =
  "GCL1_538d093018ca96dfcc7cccf5a0f772e5f1f2009eec8d02f277e9105661baa396";

export const CUTOVER_WITNESS_TRUSTED_WORKFLOW_REF =
  "lennyliu01/workos-d1-runtime/.github/workflows/cutover-witness-governed-publication-readiness.yml@refs/heads/main";
export const CUTOVER_WITNESS_GOOGLE_AUTH_ACTION_SHA =
  "7c6bc770dae815cd3e89ee6cdf493a5fab2cc093";
export const CUTOVER_WITNESS_DEPLOYMENT_PROVENANCE_MODE =
  "EXACT_ACCEPTED_MAIN_GITHUB_SHA_WITH_APPROVED_CANDIDATE_SECOND_PARENT";

export const CUTOVER_WITNESS_RUNTIME_SCOPE = Object.freeze({
  fixtureRootId: MATERIALIZED_FIXTURE_ROOT_ID,
  fixtureSpreadsheetId: MATERIALIZED_FIXTURE_SPREADSHEET_ID,
  productionDenylistId: MATERIALIZED_FIXTURE_PRODUCTION_DENYLIST_ID,
  workerService: CUTOVER_WITNESS_WORKER_SERVICE,
  formalRoute: CUTOVER_WITNESS_FORMAL_ROUTE,
  readinessRoute: CUTOVER_WITNESS_READINESS_ROUTE,
  provider: "GoogleSheetsControlPlaneProvider",
  providerPrimitiveRead: "spreadsheets.values.get/UNFORMATTED_VALUE",
  providerPrimitiveMutate: "spreadsheets.batchUpdate/updateCells",
  providerAuthMode: CUTOVER_WITNESS_PROVIDER_AUTH_MODE,
  credentialBinding: CUTOVER_WITNESS_GOOGLE_CREDENTIAL_BINDING,
  credentialProvisioning: CUTOVER_WITNESS_CREDENTIAL_PROVISIONING_MECHANISM,
  credentialLifecycleId: CUTOVER_WITNESS_CREDENTIAL_LIFECYCLE_ID,
  wifPoolFullName: CUTOVER_WITNESS_WIF_POOL_FULL_NAME,
  wifProviderFullName: CUTOVER_WITNESS_WIF_PROVIDER_FULL_NAME,
  servicePrincipal: CUTOVER_WITNESS_SERVICE_PRINCIPAL,
  googleScope: CUTOVER_WITNESS_GOOGLE_SCOPE,
  requestedAccessTokenLifetimeSeconds:
    CUTOVER_WITNESS_REQUESTED_ACCESS_TOKEN_LIFETIME_SECONDS,
  expiryMarginSeconds: CUTOVER_WITNESS_EXPIRY_MARGIN_SECONDS,
} as const);
